sudo: required
language: node_js
node_js:
  - '8'
services:
  - docker

before_install:
  - docker build -t andreasgarvik/docker_with_travis -f Dockerfile.dev .
script:
  - docker run -e CI=true andreasgarvik/docker_with_travis npm run test -- --watchAll=false
